name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Terraform workspace to destroy"
        required: true
        type: choice
        options:
          - dev
          - prod

      confirm:
        description: 'Type "DESTROY" to confirm'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    env:
      TF_WORKSPACE: ${{ inputs.environment }}
      AWS_REGION: ap-south-1

    steps:
      - name: Verify confirmation
        run: |
          if [ "${{ inputs.confirm }}" != "DESTROY" ]; then
            echo 'You must type "DESTROY" to continue.'
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan Destroy
        run: terraform plan -destroy

      - name: Terraform Destroy
        run: terraform destroy -auto-approve